#starts off with dev so that we can differntiate in app engine.  As app engine cuts words off.
application: sketchframework-test
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: testFiles.app

- url: /testList
  script: testFiles.app

- url: /html
  static_dir: src/html

- url: /src/test/web
  static_dir: src/test/web
  application_readable: true

- url: /src
  static_dir: src/main/js

- url: /test
  static_dir: src/test/web
  application_readable: true

- url: /bower_components
  static_dir: bower_components

- url: /*
  script: testFiles.app
